// This file is auto-generated by a script. Do not edit manually.

import { registerIcon } from '@minimalist-ui/core';

// --- Re-export all icons and components ---
export { minAlertSolid, AlertIconSolid } from '@minimalist-ui/core/icons/solid/AlertIconSolid';
export { minArrowDownSolid, ArrowDownIconSolid } from '@minimalist-ui/core/icons/solid/ArrowDownIconSolid';
export { minArrowLeftSolid, ArrowLeftIconSolid } from '@minimalist-ui/core/icons/solid/ArrowLeftIconSolid';
export { minArrowRightSolid, ArrowRightIconSolid } from '@minimalist-ui/core/icons/solid/ArrowRightIconSolid';
export { minArrowUpSolid, ArrowUpIconSolid } from '@minimalist-ui/core/icons/solid/ArrowUpIconSolid';
export { minBackSolid, BackIconSolid } from '@minimalist-ui/core/icons/solid/BackIconSolid';
export { minBatterySolid, BatteryIconSolid } from '@minimalist-ui/core/icons/solid/BatteryIconSolid';
export { minBellSolid, BellIconSolid } from '@minimalist-ui/core/icons/solid/BellIconSolid';
export { minCameraSolid, CameraIconSolid } from '@minimalist-ui/core/icons/solid/CameraIconSolid';
export { minCheckSolid, CheckIconSolid } from '@minimalist-ui/core/icons/solid/CheckIconSolid';
export { minChevronDownSolid, ChevronDownIconSolid } from '@minimalist-ui/core/icons/solid/ChevronDownIconSolid';
export { minChevronLeftSolid, ChevronLeftIconSolid } from '@minimalist-ui/core/icons/solid/ChevronLeftIconSolid';
export { minChevronRightSolid, ChevronRightIconSolid } from '@minimalist-ui/core/icons/solid/ChevronRightIconSolid';
export { minChevronUpSolid, ChevronUpIconSolid } from '@minimalist-ui/core/icons/solid/ChevronUpIconSolid';
export { minClipboardSolid, ClipboardIconSolid } from '@minimalist-ui/core/icons/solid/ClipboardIconSolid';
export { minCloseSolid, CloseIconSolid } from '@minimalist-ui/core/icons/solid/CloseIconSolid';
export { minCloudSolid, CloudIconSolid } from '@minimalist-ui/core/icons/solid/CloudIconSolid';
export { minDownloadSolid, DownloadIconSolid } from '@minimalist-ui/core/icons/solid/DownloadIconSolid';
export { minEyeSolid, EyeIconSolid } from '@minimalist-ui/core/icons/solid/EyeIconSolid';
export { minEyeOffSolid, EyeOffIconSolid } from '@minimalist-ui/core/icons/solid/EyeOffIconSolid';
export { minFastForwardSolid, FastForwardIconSolid } from '@minimalist-ui/core/icons/solid/FastForwardIconSolid';
export { minFileSolid, FileIconSolid } from '@minimalist-ui/core/icons/solid/FileIconSolid';
export { minFolderSolid, FolderIconSolid } from '@minimalist-ui/core/icons/solid/FolderIconSolid';
export { minForwardSolid, ForwardIconSolid } from '@minimalist-ui/core/icons/solid/ForwardIconSolid';
export { minHeartSolid, HeartIconSolid } from '@minimalist-ui/core/icons/solid/HeartIconSolid';
export { minHomeSolid, HomeIconSolid } from '@minimalist-ui/core/icons/solid/HomeIconSolid';
export { minImageSolid, ImageIconSolid } from '@minimalist-ui/core/icons/solid/ImageIconSolid';
export { minInfoSolid, InfoIconSolid } from '@minimalist-ui/core/icons/solid/InfoIconSolid';
export { minLoaderSolid, LoaderIconSolid } from '@minimalist-ui/core/icons/solid/LoaderIconSolid';
export { minLockSolid, LockIconSolid } from '@minimalist-ui/core/icons/solid/LockIconSolid';
export { minMailSolid, MailIconSolid } from '@minimalist-ui/core/icons/solid/MailIconSolid';
export { minMenuSolid, MenuIconSolid } from '@minimalist-ui/core/icons/solid/MenuIconSolid';
export { minMessageSolid, MessageIconSolid } from '@minimalist-ui/core/icons/solid/MessageIconSolid';
export { minMinusSolid, MinusIconSolid } from '@minimalist-ui/core/icons/solid/MinusIconSolid';
export { minMuteSolid, MuteIconSolid } from '@minimalist-ui/core/icons/solid/MuteIconSolid';
export { minPauseSolid, PauseIconSolid } from '@minimalist-ui/core/icons/solid/PauseIconSolid';
export { minPhoneSolid, PhoneIconSolid } from '@minimalist-ui/core/icons/solid/PhoneIconSolid';
export { minPlaySolid, PlayIconSolid } from '@minimalist-ui/core/icons/solid/PlayIconSolid';
export { minPlusSolid, PlusIconSolid } from '@minimalist-ui/core/icons/solid/PlusIconSolid';
export { minPrintSolid, PrintIconSolid } from '@minimalist-ui/core/icons/solid/PrintIconSolid';
export { minRefreshSolid, RefreshIconSolid } from '@minimalist-ui/core/icons/solid/RefreshIconSolid';
export { minRewindSolid, RewindIconSolid } from '@minimalist-ui/core/icons/solid/RewindIconSolid';
export { minSaveSolid, SaveIconSolid } from '@minimalist-ui/core/icons/solid/SaveIconSolid';
export { minSearchSolid, SearchIconSolid } from '@minimalist-ui/core/icons/solid/SearchIconSolid';
export { minSettingsSolid, SettingsIconSolid } from '@minimalist-ui/core/icons/solid/SettingsIconSolid';
export { minShareSolid, ShareIconSolid } from '@minimalist-ui/core/icons/solid/ShareIconSolid';
export { minStarSolid, StarIconSolid } from '@minimalist-ui/core/icons/solid/StarIconSolid';
export { minStopSolid, StopIconSolid } from '@minimalist-ui/core/icons/solid/StopIconSolid';
export { minTrashSolid, TrashIconSolid } from '@minimalist-ui/core/icons/solid/TrashIconSolid';
export { minUnlockSolid, UnlockIconSolid } from '@minimalist-ui/core/icons/solid/UnlockIconSolid';
export { minUploadSolid, UploadIconSolid } from '@minimalist-ui/core/icons/solid/UploadIconSolid';
export { minUserSolid, UserIconSolid } from '@minimalist-ui/core/icons/solid/UserIconSolid';
export { minVolumeSolid, VolumeIconSolid } from '@minimalist-ui/core/icons/solid/VolumeIconSolid';
export { minWifiSolid, WifiIconSolid } from '@minimalist-ui/core/icons/solid/WifiIconSolid';

// --- Import icon objects for registration ---
import { minAlertSolid } from '@minimalist-ui/core/icons/solid/AlertIconSolid';
import { minArrowDownSolid } from '@minimalist-ui/core/icons/solid/ArrowDownIconSolid';
import { minArrowLeftSolid } from '@minimalist-ui/core/icons/solid/ArrowLeftIconSolid';
import { minArrowRightSolid } from '@minimalist-ui/core/icons/solid/ArrowRightIconSolid';
import { minArrowUpSolid } from '@minimalist-ui/core/icons/solid/ArrowUpIconSolid';
import { minBackSolid } from '@minimalist-ui/core/icons/solid/BackIconSolid';
import { minBatterySolid } from '@minimalist-ui/core/icons/solid/BatteryIconSolid';
import { minBellSolid } from '@minimalist-ui/core/icons/solid/BellIconSolid';
import { minCameraSolid } from '@minimalist-ui/core/icons/solid/CameraIconSolid';
import { minCheckSolid } from '@minimalist-ui/core/icons/solid/CheckIconSolid';
import { minChevronDownSolid } from '@minimalist-ui/core/icons/solid/ChevronDownIconSolid';
import { minChevronLeftSolid } from '@minimalist-ui/core/icons/solid/ChevronLeftIconSolid';
import { minChevronRightSolid } from '@minimalist-ui/core/icons/solid/ChevronRightIconSolid';
import { minChevronUpSolid } from '@minimalist-ui/core/icons/solid/ChevronUpIconSolid';
import { minClipboardSolid } from '@minimalist-ui/core/icons/solid/ClipboardIconSolid';
import { minCloseSolid } from '@minimalist-ui/core/icons/solid/CloseIconSolid';
import { minCloudSolid } from '@minimalist-ui/core/icons/solid/CloudIconSolid';
import { minDownloadSolid } from '@minimalist-ui/core/icons/solid/DownloadIconSolid';
import { minEyeSolid } from '@minimalist-ui/core/icons/solid/EyeIconSolid';
import { minEyeOffSolid } from '@minimalist-ui/core/icons/solid/EyeOffIconSolid';
import { minFastForwardSolid } from '@minimalist-ui/core/icons/solid/FastForwardIconSolid';
import { minFileSolid } from '@minimalist-ui/core/icons/solid/FileIconSolid';
import { minFolderSolid } from '@minimalist-ui/core/icons/solid/FolderIconSolid';
import { minForwardSolid } from '@minimalist-ui/core/icons/solid/ForwardIconSolid';
import { minHeartSolid } from '@minimalist-ui/core/icons/solid/HeartIconSolid';
import { minHomeSolid } from '@minimalist-ui/core/icons/solid/HomeIconSolid';
import { minImageSolid } from '@minimalist-ui/core/icons/solid/ImageIconSolid';
import { minInfoSolid } from '@minimalist-ui/core/icons/solid/InfoIconSolid';
import { minLoaderSolid } from '@minimalist-ui/core/icons/solid/LoaderIconSolid';
import { minLockSolid } from '@minimalist-ui/core/icons/solid/LockIconSolid';
import { minMailSolid } from '@minimalist-ui/core/icons/solid/MailIconSolid';
import { minMenuSolid } from '@minimalist-ui/core/icons/solid/MenuIconSolid';
import { minMessageSolid } from '@minimalist-ui/core/icons/solid/MessageIconSolid';
import { minMinusSolid } from '@minimalist-ui/core/icons/solid/MinusIconSolid';
import { minMuteSolid } from '@minimalist-ui/core/icons/solid/MuteIconSolid';
import { minPauseSolid } from '@minimalist-ui/core/icons/solid/PauseIconSolid';
import { minPhoneSolid } from '@minimalist-ui/core/icons/solid/PhoneIconSolid';
import { minPlaySolid } from '@minimalist-ui/core/icons/solid/PlayIconSolid';
import { minPlusSolid } from '@minimalist-ui/core/icons/solid/PlusIconSolid';
import { minPrintSolid } from '@minimalist-ui/core/icons/solid/PrintIconSolid';
import { minRefreshSolid } from '@minimalist-ui/core/icons/solid/RefreshIconSolid';
import { minRewindSolid } from '@minimalist-ui/core/icons/solid/RewindIconSolid';
import { minSaveSolid } from '@minimalist-ui/core/icons/solid/SaveIconSolid';
import { minSearchSolid } from '@minimalist-ui/core/icons/solid/SearchIconSolid';
import { minSettingsSolid } from '@minimalist-ui/core/icons/solid/SettingsIconSolid';
import { minShareSolid } from '@minimalist-ui/core/icons/solid/ShareIconSolid';
import { minStarSolid } from '@minimalist-ui/core/icons/solid/StarIconSolid';
import { minStopSolid } from '@minimalist-ui/core/icons/solid/StopIconSolid';
import { minTrashSolid } from '@minimalist-ui/core/icons/solid/TrashIconSolid';
import { minUnlockSolid } from '@minimalist-ui/core/icons/solid/UnlockIconSolid';
import { minUploadSolid } from '@minimalist-ui/core/icons/solid/UploadIconSolid';
import { minUserSolid } from '@minimalist-ui/core/icons/solid/UserIconSolid';
import { minVolumeSolid } from '@minimalist-ui/core/icons/solid/VolumeIconSolid';
import { minWifiSolid } from '@minimalist-ui/core/icons/solid/WifiIconSolid';

// --- Register all icons ---
const solidIcons = [
    minAlertSolid,
    minArrowDownSolid,
    minArrowLeftSolid,
    minArrowRightSolid,
    minArrowUpSolid,
    minBackSolid,
    minBatterySolid,
    minBellSolid,
    minCameraSolid,
    minCheckSolid,
    minChevronDownSolid,
    minChevronLeftSolid,
    minChevronRightSolid,
    minChevronUpSolid,
    minClipboardSolid,
    minCloseSolid,
    minCloudSolid,
    minDownloadSolid,
    minEyeSolid,
    minEyeOffSolid,
    minFastForwardSolid,
    minFileSolid,
    minFolderSolid,
    minForwardSolid,
    minHeartSolid,
    minHomeSolid,
    minImageSolid,
    minInfoSolid,
    minLoaderSolid,
    minLockSolid,
    minMailSolid,
    minMenuSolid,
    minMessageSolid,
    minMinusSolid,
    minMuteSolid,
    minPauseSolid,
    minPhoneSolid,
    minPlaySolid,
    minPlusSolid,
    minPrintSolid,
    minRefreshSolid,
    minRewindSolid,
    minSaveSolid,
    minSearchSolid,
    minSettingsSolid,
    minShareSolid,
    minStarSolid,
    minStopSolid,
    minTrashSolid,
    minUnlockSolid,
    minUploadSolid,
    minUserSolid,
    minVolumeSolid,
    minWifiSolid
];

solidIcons.forEach((icon) => registerIcon(icon));
