// This file is auto-generated by a script. Do not edit manually.

import { registerIcon } from '@minimalist-ui/core';

// --- Re-export all icons and components ---
export { minAlertOutline, AlertIconOutline } from '@minimalist-ui/core/icons/outline/AlertIconOutline';
export { minArrowDownOutline, ArrowDownIconOutline } from '@minimalist-ui/core/icons/outline/ArrowDownIconOutline';
export { minArrowLeftOutline, ArrowLeftIconOutline } from '@minimalist-ui/core/icons/outline/ArrowLeftIconOutline';
export { minArrowRightOutline, ArrowRightIconOutline } from '@minimalist-ui/core/icons/outline/ArrowRightIconOutline';
export { minArrowUpOutline, ArrowUpIconOutline } from '@minimalist-ui/core/icons/outline/ArrowUpIconOutline';
export { minBackOutline, BackIconOutline } from '@minimalist-ui/core/icons/outline/BackIconOutline';
export { minBatteryOutline, BatteryIconOutline } from '@minimalist-ui/core/icons/outline/BatteryIconOutline';
export { minBellOutline, BellIconOutline } from '@minimalist-ui/core/icons/outline/BellIconOutline';
export { minCameraOutline, CameraIconOutline } from '@minimalist-ui/core/icons/outline/CameraIconOutline';
export { minCheckOutline, CheckIconOutline } from '@minimalist-ui/core/icons/outline/CheckIconOutline';
export {
    minChevronDownOutline,
    ChevronDownIconOutline
} from '@minimalist-ui/core/icons/outline/ChevronDownIconOutline';
export {
    minChevronLeftOutline,
    ChevronLeftIconOutline
} from '@minimalist-ui/core/icons/outline/ChevronLeftIconOutline';
export {
    minChevronRightOutline,
    ChevronRightIconOutline
} from '@minimalist-ui/core/icons/outline/ChevronRightIconOutline';
export { minChevronUpOutline, ChevronUpIconOutline } from '@minimalist-ui/core/icons/outline/ChevronUpIconOutline';
export { minClipboardOutline, ClipboardIconOutline } from '@minimalist-ui/core/icons/outline/ClipboardIconOutline';
export { minCloseOutline, CloseIconOutline } from '@minimalist-ui/core/icons/outline/CloseIconOutline';
export { minCloudOutline, CloudIconOutline } from '@minimalist-ui/core/icons/outline/CloudIconOutline';
export { minDownloadOutline, DownloadIconOutline } from '@minimalist-ui/core/icons/outline/DownloadIconOutline';
export { minEyeOutline, EyeIconOutline } from '@minimalist-ui/core/icons/outline/EyeIconOutline';
export { minEyeOffOutline, EyeOffIconOutline } from '@minimalist-ui/core/icons/outline/EyeOffIconOutline';
export {
    minFastForwardOutline,
    FastForwardIconOutline
} from '@minimalist-ui/core/icons/outline/FastForwardIconOutline';
export { minFileOutline, FileIconOutline } from '@minimalist-ui/core/icons/outline/FileIconOutline';
export { minFolderOutline, FolderIconOutline } from '@minimalist-ui/core/icons/outline/FolderIconOutline';
export { minForwardOutline, ForwardIconOutline } from '@minimalist-ui/core/icons/outline/ForwardIconOutline';
export { minHeartOutline, HeartIconOutline } from '@minimalist-ui/core/icons/outline/HeartIconOutline';
export { minHomeOutline, HomeIconOutline } from '@minimalist-ui/core/icons/outline/HomeIconOutline';
export { minImageOutline, ImageIconOutline } from '@minimalist-ui/core/icons/outline/ImageIconOutline';
export { minInfoOutline, InfoIconOutline } from '@minimalist-ui/core/icons/outline/InfoIconOutline';
export { minLoaderOutline, LoaderIconOutline } from '@minimalist-ui/core/icons/outline/LoaderIconOutline';
export { minLockOutline, LockIconOutline } from '@minimalist-ui/core/icons/outline/LockIconOutline';
export { minMailOutline, MailIconOutline } from '@minimalist-ui/core/icons/outline/MailIconOutline';
export { minMenuOutline, MenuIconOutline } from '@minimalist-ui/core/icons/outline/MenuIconOutline';
export { minMessageOutline, MessageIconOutline } from '@minimalist-ui/core/icons/outline/MessageIconOutline';
export { minMinusOutline, MinusIconOutline } from '@minimalist-ui/core/icons/outline/MinusIconOutline';
export { minMuteOutline, MuteIconOutline } from '@minimalist-ui/core/icons/outline/MuteIconOutline';
export { minPauseOutline, PauseIconOutline } from '@minimalist-ui/core/icons/outline/PauseIconOutline';
export { minPhoneOutline, PhoneIconOutline } from '@minimalist-ui/core/icons/outline/PhoneIconOutline';
export { minPlayOutline, PlayIconOutline } from '@minimalist-ui/core/icons/outline/PlayIconOutline';
export { minPlusOutline, PlusIconOutline } from '@minimalist-ui/core/icons/outline/PlusIconOutline';
export { minPrintOutline, PrintIconOutline } from '@minimalist-ui/core/icons/outline/PrintIconOutline';
export { minRefreshOutline, RefreshIconOutline } from '@minimalist-ui/core/icons/outline/RefreshIconOutline';
export { minRewindOutline, RewindIconOutline } from '@minimalist-ui/core/icons/outline/RewindIconOutline';
export { minSaveOutline, SaveIconOutline } from '@minimalist-ui/core/icons/outline/SaveIconOutline';
export { minSearchOutline, SearchIconOutline } from '@minimalist-ui/core/icons/outline/SearchIconOutline';
export { minSettingsOutline, SettingsIconOutline } from '@minimalist-ui/core/icons/outline/SettingsIconOutline';
export { minShareOutline, ShareIconOutline } from '@minimalist-ui/core/icons/outline/ShareIconOutline';
export { minStarOutline, StarIconOutline } from '@minimalist-ui/core/icons/outline/StarIconOutline';
export { minStopOutline, StopIconOutline } from '@minimalist-ui/core/icons/outline/StopIconOutline';
export { minTrashOutline, TrashIconOutline } from '@minimalist-ui/core/icons/outline/TrashIconOutline';
export { minUnlockOutline, UnlockIconOutline } from '@minimalist-ui/core/icons/outline/UnlockIconOutline';
export { minUploadOutline, UploadIconOutline } from '@minimalist-ui/core/icons/outline/UploadIconOutline';
export { minUserOutline, UserIconOutline } from '@minimalist-ui/core/icons/outline/UserIconOutline';
export { minVolumeOutline, VolumeIconOutline } from '@minimalist-ui/core/icons/outline/VolumeIconOutline';
export { minWifiOutline, WifiIconOutline } from '@minimalist-ui/core/icons/outline/WifiIconOutline';

// --- Import icon objects for registration ---
import { minAlertOutline } from '@minimalist-ui/core/icons/outline/AlertIconOutline';
import { minArrowDownOutline } from '@minimalist-ui/core/icons/outline/ArrowDownIconOutline';
import { minArrowLeftOutline } from '@minimalist-ui/core/icons/outline/ArrowLeftIconOutline';
import { minArrowRightOutline } from '@minimalist-ui/core/icons/outline/ArrowRightIconOutline';
import { minArrowUpOutline } from '@minimalist-ui/core/icons/outline/ArrowUpIconOutline';
import { minBackOutline } from '@minimalist-ui/core/icons/outline/BackIconOutline';
import { minBatteryOutline } from '@minimalist-ui/core/icons/outline/BatteryIconOutline';
import { minBellOutline } from '@minimalist-ui/core/icons/outline/BellIconOutline';
import { minCameraOutline } from '@minimalist-ui/core/icons/outline/CameraIconOutline';
import { minCheckOutline } from '@minimalist-ui/core/icons/outline/CheckIconOutline';
import { minChevronDownOutline } from '@minimalist-ui/core/icons/outline/ChevronDownIconOutline';
import { minChevronLeftOutline } from '@minimalist-ui/core/icons/outline/ChevronLeftIconOutline';
import { minChevronRightOutline } from '@minimalist-ui/core/icons/outline/ChevronRightIconOutline';
import { minChevronUpOutline } from '@minimalist-ui/core/icons/outline/ChevronUpIconOutline';
import { minClipboardOutline } from '@minimalist-ui/core/icons/outline/ClipboardIconOutline';
import { minCloseOutline } from '@minimalist-ui/core/icons/outline/CloseIconOutline';
import { minCloudOutline } from '@minimalist-ui/core/icons/outline/CloudIconOutline';
import { minDownloadOutline } from '@minimalist-ui/core/icons/outline/DownloadIconOutline';
import { minEyeOutline } from '@minimalist-ui/core/icons/outline/EyeIconOutline';
import { minEyeOffOutline } from '@minimalist-ui/core/icons/outline/EyeOffIconOutline';
import { minFastForwardOutline } from '@minimalist-ui/core/icons/outline/FastForwardIconOutline';
import { minFileOutline } from '@minimalist-ui/core/icons/outline/FileIconOutline';
import { minFolderOutline } from '@minimalist-ui/core/icons/outline/FolderIconOutline';
import { minForwardOutline } from '@minimalist-ui/core/icons/outline/ForwardIconOutline';
import { minHeartOutline } from '@minimalist-ui/core/icons/outline/HeartIconOutline';
import { minHomeOutline } from '@minimalist-ui/core/icons/outline/HomeIconOutline';
import { minImageOutline } from '@minimalist-ui/core/icons/outline/ImageIconOutline';
import { minInfoOutline } from '@minimalist-ui/core/icons/outline/InfoIconOutline';
import { minLoaderOutline } from '@minimalist-ui/core/icons/outline/LoaderIconOutline';
import { minLockOutline } from '@minimalist-ui/core/icons/outline/LockIconOutline';
import { minMailOutline } from '@minimalist-ui/core/icons/outline/MailIconOutline';
import { minMenuOutline } from '@minimalist-ui/core/icons/outline/MenuIconOutline';
import { minMessageOutline } from '@minimalist-ui/core/icons/outline/MessageIconOutline';
import { minMinusOutline } from '@minimalist-ui/core/icons/outline/MinusIconOutline';
import { minMuteOutline } from '@minimalist-ui/core/icons/outline/MuteIconOutline';
import { minPauseOutline } from '@minimalist-ui/core/icons/outline/PauseIconOutline';
import { minPhoneOutline } from '@minimalist-ui/core/icons/outline/PhoneIconOutline';
import { minPlayOutline } from '@minimalist-ui/core/icons/outline/PlayIconOutline';
import { minPlusOutline } from '@minimalist-ui/core/icons/outline/PlusIconOutline';
import { minPrintOutline } from '@minimalist-ui/core/icons/outline/PrintIconOutline';
import { minRefreshOutline } from '@minimalist-ui/core/icons/outline/RefreshIconOutline';
import { minRewindOutline } from '@minimalist-ui/core/icons/outline/RewindIconOutline';
import { minSaveOutline } from '@minimalist-ui/core/icons/outline/SaveIconOutline';
import { minSearchOutline } from '@minimalist-ui/core/icons/outline/SearchIconOutline';
import { minSettingsOutline } from '@minimalist-ui/core/icons/outline/SettingsIconOutline';
import { minShareOutline } from '@minimalist-ui/core/icons/outline/ShareIconOutline';
import { minStarOutline } from '@minimalist-ui/core/icons/outline/StarIconOutline';
import { minStopOutline } from '@minimalist-ui/core/icons/outline/StopIconOutline';
import { minTrashOutline } from '@minimalist-ui/core/icons/outline/TrashIconOutline';
import { minUnlockOutline } from '@minimalist-ui/core/icons/outline/UnlockIconOutline';
import { minUploadOutline } from '@minimalist-ui/core/icons/outline/UploadIconOutline';
import { minUserOutline } from '@minimalist-ui/core/icons/outline/UserIconOutline';
import { minVolumeOutline } from '@minimalist-ui/core/icons/outline/VolumeIconOutline';
import { minWifiOutline } from '@minimalist-ui/core/icons/outline/WifiIconOutline';

// --- Register all icons ---
const outlineIcons = [
    minAlertOutline,
    minArrowDownOutline,
    minArrowLeftOutline,
    minArrowRightOutline,
    minArrowUpOutline,
    minBackOutline,
    minBatteryOutline,
    minBellOutline,
    minCameraOutline,
    minCheckOutline,
    minChevronDownOutline,
    minChevronLeftOutline,
    minChevronRightOutline,
    minChevronUpOutline,
    minClipboardOutline,
    minCloseOutline,
    minCloudOutline,
    minDownloadOutline,
    minEyeOutline,
    minEyeOffOutline,
    minFastForwardOutline,
    minFileOutline,
    minFolderOutline,
    minForwardOutline,
    minHeartOutline,
    minHomeOutline,
    minImageOutline,
    minInfoOutline,
    minLoaderOutline,
    minLockOutline,
    minMailOutline,
    minMenuOutline,
    minMessageOutline,
    minMinusOutline,
    minMuteOutline,
    minPauseOutline,
    minPhoneOutline,
    minPlayOutline,
    minPlusOutline,
    minPrintOutline,
    minRefreshOutline,
    minRewindOutline,
    minSaveOutline,
    minSearchOutline,
    minSettingsOutline,
    minShareOutline,
    minStarOutline,
    minStopOutline,
    minTrashOutline,
    minUnlockOutline,
    minUploadOutline,
    minUserOutline,
    minVolumeOutline,
    minWifiOutline
];

outlineIcons.forEach((icon) => registerIcon(icon));
