// This file is auto-generated by a script. Do not edit manually.

import { registerIcon } from '@minimalist-ui/core';
export * from '@minimalist-ui/core/icons/utils';

export * from '@minimalist-ui/core/icons/solid';
export * from '@minimalist-ui/core/icons/outline';

// --- Re-export all icons and components ---
export { minAlert, AlertIcon } from '@minimalist-ui/core/icons/AlertIcon';
export { minArrowDown, ArrowDownIcon } from '@minimalist-ui/core/icons/ArrowDownIcon';
export { minArrowLeft, ArrowLeftIcon } from '@minimalist-ui/core/icons/ArrowLeftIcon';
export { minArrowRight, ArrowRightIcon } from '@minimalist-ui/core/icons/ArrowRightIcon';
export { minArrowUp, ArrowUpIcon } from '@minimalist-ui/core/icons/ArrowUpIcon';
export { minBack, BackIcon } from '@minimalist-ui/core/icons/BackIcon';
export { minBattery, BatteryIcon } from '@minimalist-ui/core/icons/BatteryIcon';
export { minBell, BellIcon } from '@minimalist-ui/core/icons/BellIcon';
export { minCamera, CameraIcon } from '@minimalist-ui/core/icons/CameraIcon';
export { minCheck, CheckIcon } from '@minimalist-ui/core/icons/CheckIcon';
export { minChevronDown, ChevronDownIcon } from '@minimalist-ui/core/icons/ChevronDownIcon';
export { minChevronLeft, ChevronLeftIcon } from '@minimalist-ui/core/icons/ChevronLeftIcon';
export { minChevronRight, ChevronRightIcon } from '@minimalist-ui/core/icons/ChevronRightIcon';
export { minChevronUp, ChevronUpIcon } from '@minimalist-ui/core/icons/ChevronUpIcon';
export { minClipboard, ClipboardIcon } from '@minimalist-ui/core/icons/ClipboardIcon';
export { minClose, CloseIcon } from '@minimalist-ui/core/icons/CloseIcon';
export { minCloud, CloudIcon } from '@minimalist-ui/core/icons/CloudIcon';
export { minDownload, DownloadIcon } from '@minimalist-ui/core/icons/DownloadIcon';
export { minEye, EyeIcon } from '@minimalist-ui/core/icons/EyeIcon';
export { minEyeOff, EyeOffIcon } from '@minimalist-ui/core/icons/EyeOffIcon';
export { minFastForward, FastForwardIcon } from '@minimalist-ui/core/icons/FastForwardIcon';
export { minFile, FileIcon } from '@minimalist-ui/core/icons/FileIcon';
export { minFolder, FolderIcon } from '@minimalist-ui/core/icons/FolderIcon';
export { minForward, ForwardIcon } from '@minimalist-ui/core/icons/ForwardIcon';
export { minHeart, HeartIcon } from '@minimalist-ui/core/icons/HeartIcon';
export { minHome, HomeIcon } from '@minimalist-ui/core/icons/HomeIcon';
export { minImage, ImageIcon } from '@minimalist-ui/core/icons/ImageIcon';
export { minInfo, InfoIcon } from '@minimalist-ui/core/icons/InfoIcon';
export { minLoader, LoaderIcon } from '@minimalist-ui/core/icons/LoaderIcon';
export { minLock, LockIcon } from '@minimalist-ui/core/icons/LockIcon';
export { minMail, MailIcon } from '@minimalist-ui/core/icons/MailIcon';
export { minMenu, MenuIcon } from '@minimalist-ui/core/icons/MenuIcon';
export { minMessage, MessageIcon } from '@minimalist-ui/core/icons/MessageIcon';
export { minMinus, MinusIcon } from '@minimalist-ui/core/icons/MinusIcon';
export { minMute, MuteIcon } from '@minimalist-ui/core/icons/MuteIcon';
export { minPause, PauseIcon } from '@minimalist-ui/core/icons/PauseIcon';
export { minPhone, PhoneIcon } from '@minimalist-ui/core/icons/PhoneIcon';
export { minPlay, PlayIcon } from '@minimalist-ui/core/icons/PlayIcon';
export { minPlus, PlusIcon } from '@minimalist-ui/core/icons/PlusIcon';
export { minPrint, PrintIcon } from '@minimalist-ui/core/icons/PrintIcon';
export { minRefresh, RefreshIcon } from '@minimalist-ui/core/icons/RefreshIcon';
export { minRewind, RewindIcon } from '@minimalist-ui/core/icons/RewindIcon';
export { minSave, SaveIcon } from '@minimalist-ui/core/icons/SaveIcon';
export { minSearch, SearchIcon } from '@minimalist-ui/core/icons/SearchIcon';
export { minSettings, SettingsIcon } from '@minimalist-ui/core/icons/SettingsIcon';
export { minShare, ShareIcon } from '@minimalist-ui/core/icons/ShareIcon';
export { minStar, StarIcon } from '@minimalist-ui/core/icons/StarIcon';
export { minStop, StopIcon } from '@minimalist-ui/core/icons/StopIcon';
export { minTrash, TrashIcon } from '@minimalist-ui/core/icons/TrashIcon';
export { minUnlock, UnlockIcon } from '@minimalist-ui/core/icons/UnlockIcon';
export { minUpload, UploadIcon } from '@minimalist-ui/core/icons/UploadIcon';
export { minUser, UserIcon } from '@minimalist-ui/core/icons/UserIcon';
export { minVolume, VolumeIcon } from '@minimalist-ui/core/icons/VolumeIcon';
export { minWifi, WifiIcon } from '@minimalist-ui/core/icons/WifiIcon';

// --- Import icon objects for registration ---
import { minAlert } from '@minimalist-ui/core/icons/AlertIcon';
import { minArrowDown } from '@minimalist-ui/core/icons/ArrowDownIcon';
import { minArrowLeft } from '@minimalist-ui/core/icons/ArrowLeftIcon';
import { minArrowRight } from '@minimalist-ui/core/icons/ArrowRightIcon';
import { minArrowUp } from '@minimalist-ui/core/icons/ArrowUpIcon';
import { minBack } from '@minimalist-ui/core/icons/BackIcon';
import { minBattery } from '@minimalist-ui/core/icons/BatteryIcon';
import { minBell } from '@minimalist-ui/core/icons/BellIcon';
import { minCamera } from '@minimalist-ui/core/icons/CameraIcon';
import { minCheck } from '@minimalist-ui/core/icons/CheckIcon';
import { minChevronDown } from '@minimalist-ui/core/icons/ChevronDownIcon';
import { minChevronLeft } from '@minimalist-ui/core/icons/ChevronLeftIcon';
import { minChevronRight } from '@minimalist-ui/core/icons/ChevronRightIcon';
import { minChevronUp } from '@minimalist-ui/core/icons/ChevronUpIcon';
import { minClipboard } from '@minimalist-ui/core/icons/ClipboardIcon';
import { minClose } from '@minimalist-ui/core/icons/CloseIcon';
import { minCloud } from '@minimalist-ui/core/icons/CloudIcon';
import { minDownload } from '@minimalist-ui/core/icons/DownloadIcon';
import { minEye } from '@minimalist-ui/core/icons/EyeIcon';
import { minEyeOff } from '@minimalist-ui/core/icons/EyeOffIcon';
import { minFastForward } from '@minimalist-ui/core/icons/FastForwardIcon';
import { minFile } from '@minimalist-ui/core/icons/FileIcon';
import { minFolder } from '@minimalist-ui/core/icons/FolderIcon';
import { minForward } from '@minimalist-ui/core/icons/ForwardIcon';
import { minHeart } from '@minimalist-ui/core/icons/HeartIcon';
import { minHome } from '@minimalist-ui/core/icons/HomeIcon';
import { minImage } from '@minimalist-ui/core/icons/ImageIcon';
import { minInfo } from '@minimalist-ui/core/icons/InfoIcon';
import { minLoader } from '@minimalist-ui/core/icons/LoaderIcon';
import { minLock } from '@minimalist-ui/core/icons/LockIcon';
import { minMail } from '@minimalist-ui/core/icons/MailIcon';
import { minMenu } from '@minimalist-ui/core/icons/MenuIcon';
import { minMessage } from '@minimalist-ui/core/icons/MessageIcon';
import { minMinus } from '@minimalist-ui/core/icons/MinusIcon';
import { minMute } from '@minimalist-ui/core/icons/MuteIcon';
import { minPause } from '@minimalist-ui/core/icons/PauseIcon';
import { minPhone } from '@minimalist-ui/core/icons/PhoneIcon';
import { minPlay } from '@minimalist-ui/core/icons/PlayIcon';
import { minPlus } from '@minimalist-ui/core/icons/PlusIcon';
import { minPrint } from '@minimalist-ui/core/icons/PrintIcon';
import { minRefresh } from '@minimalist-ui/core/icons/RefreshIcon';
import { minRewind } from '@minimalist-ui/core/icons/RewindIcon';
import { minSave } from '@minimalist-ui/core/icons/SaveIcon';
import { minSearch } from '@minimalist-ui/core/icons/SearchIcon';
import { minSettings } from '@minimalist-ui/core/icons/SettingsIcon';
import { minShare } from '@minimalist-ui/core/icons/ShareIcon';
import { minStar } from '@minimalist-ui/core/icons/StarIcon';
import { minStop } from '@minimalist-ui/core/icons/StopIcon';
import { minTrash } from '@minimalist-ui/core/icons/TrashIcon';
import { minUnlock } from '@minimalist-ui/core/icons/UnlockIcon';
import { minUpload } from '@minimalist-ui/core/icons/UploadIcon';
import { minUser } from '@minimalist-ui/core/icons/UserIcon';
import { minVolume } from '@minimalist-ui/core/icons/VolumeIcon';
import { minWifi } from '@minimalist-ui/core/icons/WifiIcon';

// --- Register all icons ---
const Icons = [
    minAlert,
    minArrowDown,
    minArrowLeft,
    minArrowRight,
    minArrowUp,
    minBack,
    minBattery,
    minBell,
    minCamera,
    minCheck,
    minChevronDown,
    minChevronLeft,
    minChevronRight,
    minChevronUp,
    minClipboard,
    minClose,
    minCloud,
    minDownload,
    minEye,
    minEyeOff,
    minFastForward,
    minFile,
    minFolder,
    minForward,
    minHeart,
    minHome,
    minImage,
    minInfo,
    minLoader,
    minLock,
    minMail,
    minMenu,
    minMessage,
    minMinus,
    minMute,
    minPause,
    minPhone,
    minPlay,
    minPlus,
    minPrint,
    minRefresh,
    minRewind,
    minSave,
    minSearch,
    minSettings,
    minShare,
    minStar,
    minStop,
    minTrash,
    minUnlock,
    minUpload,
    minUser,
    minVolume,
    minWifi
];

Icons.forEach((icon) => registerIcon(icon));
